### PR TITLE
Remove the itr macro

### LINKED ISSUE #19: Remove at-itr macro
Reasons:
1. There are [exactly](https://github.com/HHammond/DailyProgrammer-236-Balancing-Chemical-Equations/blob/084b84f2891cfb7d07350671bac92461629d309d/chem.jl) [three](https://github.com/cvdlab/LAR.jl/blob/master/src/2chain2.jl) [uses](https://github.com/krishnap25/LG-parallel) in the wild, only one of them is a package, and it's not registered
2. It's hard to maintain and I don't know how to fix it for 0.7
3. The only reason to use it is performance and I can't see a performance benefit on 0.6

```
julia> using IterTools
INFO: Recompiling stale cache file /Users/ericdavies/.julia/lib/v0.6/IterTools.ji for module IterTools.

julia> function f1(it)
           sum = zero(typeof(first(it)))
           @itr for (i, el) in enumerate(it)
               sum += i * el
           end
           return sum
       end
f1 (generic function with 1 method)

julia> function f2(it)
           sum = zero(typeof(first(it)))
           for (i, el) in enumerate(it)
               sum += i * el
           end
           return sum
       end
f2 (generic function with 1 method)

julia> x = rand(10000);

julia> using BenchmarkTools

julia> @benchmark f1($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     11.155 μs (0.00% GC)
  median time:      12.556 μs (0.00% GC)
  mean time:        13.182 μs (0.00% GC)
  maximum time:     113.474 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark f2($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     11.157 μs (0.00% GC)
  median time:      11.194 μs (0.00% GC)
  mean time:        13.010 μs (0.00% GC)
  maximum time:     2.441 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> x = rand(10);

julia> @benchmark f1($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     9.205 ns (0.00% GC)
  median time:      10.359 ns (0.00% GC)
  mean time:        10.824 ns (0.00% GC)
  maximum time:     74.991 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     998

julia> @benchmark f2($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     9.205 ns (0.00% GC)
  median time:      10.374 ns (0.00% GC)
  mean time:        11.055 ns (0.00% GC)
  maximum time:     136.026 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     998
```

### PR DESCRIPTION
**Pull request by iamed2**
Closes #19

### CODE REVIEW

**Comment by iamed2** [comment]
Alright, should be easy enough to deprecate to the same thing without the macro.

**Comment by iamed2** [comment]
I deprecated in a separate commit so we can just revert it later to kill the deprecation.

**Comment by iamed2** [comment]
Rebased. @ararslan deprecation look good?

**Comment by ararslan** [comment]
Looks like `@take` and others were also removed with deprecation. Was that intended or were they caught in the crossfire?

**Comment by iamed2** [comment]
They were never exported so I removed them without deprecation. Essentially `@itr` would internally dispatch to the appropriate macro based on the iterator function you were calling.

**Comment by ararslan** [comment]
Oh, gotcha. I'm fine with whatever, so if you're satisfied with this PR then I am too. 🙂 The deprecation looks good to me.

**Comment by iamed2** [comment]
Woo! 0.7 test success here we come!

**Pull request merged**
